gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000
  single_use: true
  token_parameter_name: refreshToken
  return_expiration: true
  return_expiration_parameter_name: refreshTokenExpiration

  # cookie:
  #   enabled: true
  #   remove_token_from_body: true
  #   # Cookie parameters
  #   http_only: true
  #   same_site: none
  #   secure: true
  #   path: /api/
  # domain: null
