vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    users:
      uri_prefix: /assets/img/users
      upload_destination: "%kernel.project_dir%/public/assets/img/users"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
    articles:
      uri_prefix: /assets/img/articles
      upload_destination: "%kernel.project_dir%/public/assets/img/articles"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
    events:
      uri_prefix: /assets/img/events
      upload_destination: "%kernel.project_dir%/public/assets/img/events"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
